# config/packages/messenger.yaml
framework:
  messenger:
    transports:
      async: "%env(MESSENGER_TRANSPORT_DSN)%"

      # or expanded to configure more options
      #async:
      #    dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
      #    options: []
